version: '3.9'
services:
  # Local development
  database:
    image: postgres
    container_name: shortener-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      # - POSTGRES_MULTIPLE_DATABASES=banq-db-test,banq-db
    ports:
      - '5432:5432'
    volumes:
      - ./.db/data:/var/lib/postgresql/data:delegated
      # - ./.db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1